#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School of the win!" | sudo tee /usr/share/nginx/html/index.html
