#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string
# Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chgrp -R ubuntu /var/www/html
sudo chmod -R g+w /var/www/html
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx stop
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
