#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a
# custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname
# of the server Nginx is running on
# Write 0-custom_http_response-header so that it configures
# a brand new Ubuntu machine to the requirements asked in
# this task
# Ignore SC2154 for shellcheck

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "29 a\\tadd_header X-Served_By $HOSTNAME:\n" /etc/nginx/sites-available/default
sudo mkdir -p /var/www/html
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
